"""Navigation layer: ticket -> gap analysis -> scenarios -> test plan.

Routes data between the deterministic tools and the LLM. It does not implement
business logic itself (BLAST Layer 2).
"""

from __future__ import annotations

import json
import os

import llm_client
from tools import gap_check, render_plan

APP_DIR = os.path.dirname(os.path.abspath(__file__))
TEMPLATE_PATH = os.path.join(APP_DIR, "templates", "test_plan_template.md")

SCENARIO_SYSTEM = """You are a Senior QA Engineer deriving test scenarios from a Jira ticket.

Output ONLY a JSON array. No prose, no markdown fences, no commentary.
Each element must have exactly these keys:
  "id"           - S-01, S-02, ... in order
  "priority"     - "P0", "P1" or "P2" (P0 = business critical)
  "trace"        - a numbered acceptance-criteria id such as "AC1" when the scenario
                   derives from the acceptance criteria above, otherwise a gap id
                   exactly as listed above, such as "G-03".
                   Never write a sentence. Never write a bare "AC".
  "scenario"     - one clear sentence describing what is being validated
  "precondition" - what must be true before the test
  "expected"     - the observable expected result

Produce between 6 and 12 scenarios. Cover positive paths, negative paths,
boundary conditions, and error handling. Never invent exact error messages,
numeric limits, or thresholds that the ticket does not state. Every "trace" must
resolve to something in the material above."""


def load_template() -> str:
    with open(TEMPLATE_PATH, "r", encoding="utf-8") as handle:
        return handle.read()


def analyze(ticket: dict) -> dict:
    """Deterministic gap analysis (tools/gap_check.py)."""
    return gap_check.analyze(ticket)


def _scenario_prompt(ticket: dict, gaps: dict) -> str:
    gap_lines = "\n".join(
        f"- {i['id']} [{i['status']}] {i['category']}: {i['statement']}"
        for i in gaps.get("items", [])
    )
    attached = (ticket.get("attachment_text") or "").strip()
    attachment_block = (
        f"\nATTACHED REQUIREMENTS (from the ticket's files — authoritative):\n{attached[:9000]}\n"
        if attached else
        "\nATTACHED REQUIREMENTS: none provided.\n"
    )
    return (
        f"ISSUE KEY: {ticket.get('issue_key', '')}\n"
        f"SUMMARY: {ticket.get('summary', '')}\n"
        f"TYPE: {ticket.get('issue_type', '')}\n"
        f"PRIORITY: {ticket.get('priority', '')}\n"
        f"LABELS: {', '.join(ticket.get('labels') or []) or 'none'}\n"
        f"COMPONENTS: {', '.join(ticket.get('components') or []) or 'none'}\n\n"
        f"ACCEPTANCE CRITERIA:\n{ticket.get('acceptance_criteria') or 'NONE FOUND IN TICKET'}\n"
        f"{attachment_block}\n"
        f"DESCRIPTION:\n{ticket.get('description_text', '')[:4000]}\n\n"
        f"GAP ANALYSIS (already performed):\n{gap_lines}\n\n"
        f"Return the JSON array of scenarios now."
    )


def _normalise_scenarios(raw, ticket: dict) -> list[dict]:
    if isinstance(raw, dict):
        raw = raw.get("scenarios") or raw.get("items") or []
    if not isinstance(raw, list):
        raise ValueError("Scenario response was not a JSON array.")

    scenarios = []
    for idx, item in enumerate(raw, start=1):
        if not isinstance(item, dict):
            continue
        text = str(item.get("scenario") or item.get("title") or "").strip()
        if not text:
            continue
        trace = item.get("trace") or item.get("traces") or []
        if isinstance(trace, str):
            trace = [trace]
        priority = str(item.get("priority", "P1")).upper()
        scenarios.append({
            "id": str(item.get("id") or f"S-{idx:02d}"),
            "priority": priority if priority in ("P0", "P1", "P2") else "P1",
            "trace": [str(t) for t in trace] or ["derived"],
            "scenario": text,
            "precondition": str(item.get("precondition") or "As described in the ticket"),
            "expected": str(item.get("expected") or item.get("expected_result") or "Behaviour matches the requirement"),
        })
    return scenarios


def generate_scenarios(settings: dict, ticket: dict, gaps: dict) -> tuple[list[dict], str, str]:
    """Ask the LLM for scenarios; fall back to deterministic derivation.

    Returns (scenarios, provider, note).
    """
    try:
        text, provider = llm_client.complete(settings, SCENARIO_SYSTEM, _scenario_prompt(ticket, gaps))
        scenarios = _normalise_scenarios(llm_client.extract_json(text), ticket)
        if scenarios:
            return scenarios, provider, f"{len(scenarios)} scenarios generated by the model."
        note = "Model returned no usable scenarios; used deterministic derivation."
    except (llm_client.LLMError, ValueError) as exc:
        provider = "none"
        note = f"LLM unavailable ({exc}); used deterministic derivation from the ticket text."

    return render_plan.derive_scenarios(ticket, gaps), provider, note


def build_plan(ticket: dict, gaps: dict, scenarios: list[dict], settings: dict) -> tuple[str, list[str]]:
    """Render the markdown test plan. Returns (markdown, unreplaced_tokens)."""
    return render_plan.render_plan(load_template(), ticket, gaps, scenarios, settings)


def build_case_prompt_seed(ticket: dict, scenarios: list[dict]) -> str:
    """Compact scenario digest reused by the case builder."""
    return json.dumps(
        [{"id": s["id"], "priority": s["priority"], "scenario": s["scenario"],
          "expected": s["expected"]} for s in scenarios],
        indent=1,
    )
